name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            os_short: win
          - os: macos
            os_short: mac
    runs-on: ${{ matrix.os }}-latest
    steps:
      - run: git config --global core.autocrlf false
        if: matrix.os == 'windows'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm version
      - run: npm ci
      - run: npm run electron:build -- --publish never
      - run: node scripts/archive.mjs ${{ matrix.os_short }} ${{ github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os}}-release
          path: dist/release-*.zip
